### ISSUE TITLE
[Feature] Show Errors

### ISSUE THREAD

**Issue by zutils** [patrickelectric/qmlonline#24]
I've been using your software - it rocks! One of the largest problems I have is that I don't know if I am typing an error or not. It would be very beneficial if I were able to see errors out in the open.

**Comment by zutils** [comment]
So I have been using this program for a while, and it only goes to show that you only find out that this exists moments after you complain about it. It exists next to the numbers when there is an error! Please forgive this post!

**Comment by patrickelectric** [comment]
Hi @zutils, I'm glad that qmlonline is helpful for you.
As you probably noted, in the left corner next to the line numbers you can see an error icon, it'll display any information about:  Runtime errors in QML, binding loop, breaking binding and etc.
![image](https://user-images.githubusercontent.com/1215497/80700763-a4b08680-8ab4-11ea-961d-a912c5434197.png)
