### ISSUE TITLE
Issues with new terminal feature

### ISSUE THREAD

**Issue by patrickelectric** [patrickelectric/qmlonline#25]
1. Cursor gets behind the terminal
    This is a bit problematic because the programmer needs to check the output while coding, it should have the same behavior as the vertical split between the code and the right canvas. 
![deepin-screen-recorder_Select area_20200501092950](https://user-images.githubusercontent.com/1215497/80805653-05ac8d00-8b8f-11ea-8e43-3465e8334b21.gif)

2. When scroll is added the resize functionality stops working.
    I have added a [debug code to replicate the issue](https://github.com/patrickelectric/qmlonline/blob/terminal/index.html#L103).
![deepin-screen-recorder_Select area_20200501093808](https://user-images.githubusercontent.com/1215497/80805879-8bc8d380-8b8f-11ea-8492-8b53c0677a1b.gif)

@biakp Can you take a look ?
There is a [terminal branch](https://github.com/patrickelectric/qmlonline/tree/terminal) for you to check the problem.
Sorry if I was not clear in my previous description.

**Comment by biakp** [comment]
Sure @patrickelectric ! 😸

**Comment by biakp** [comment]
Good night @patrickelectric! Already fixed the second problem and also changed the scroll design to match the page...but I have a problem...I understand what you want on the first issue, but you say that the canvas already does that buuut...  it doesn't for me, it covers the code just like the terminal  does... :s 
![image](https://user-images.githubusercontent.com/42621272/81351722-5ba39800-909b-11ea-9abf-c4a3494365b1.png)

**Comment by biakp** [comment]
Going to try to fix this behavior for both... 😄

**Comment by patrickelectric** [comment]
@biakp, there is a scrollbar for the text editor, but it's behind the status bar 
![image](https://user-images.githubusercontent.com/1215497/81399815-1a929e80-9102-11ea-9ea4-8dc3b22ffef8.png)

**Comment by biakp** [comment]
Oh I see :c it doesn't show on my... 
![image](https://user-images.githubusercontent.com/42621272/81454409-90c6ed80-9162-11ea-80ff-e05f2daf87e5.png)

**Comment by biakp** [comment]
@patrickelectric I searched till 4 am last night something to make it work properly haha I will be trying a fix I found for the ace editor.

**Comment by biakp** [comment]
There are plenty of bugs when I try to make it go up :S because of all the layers inside the ace editor

**Comment by patrickelectric** [comment]
Hi @biakp, thank you for the update and your hard work on it.
But, it's necessary to deal with the editor ? Could we create something like this: https://metroui.org.ua/splitter.html
Check the **combine split** example.
I believe that this could work for now, let me know what you thinks.

**Comment by patrickelectric** [comment]
Also, as a suggestion, try to not spend more than 1 hour trying to figure out something, I usually take a break or I try to figure it out later, and in my next attempts, I usually come with a solution faster. 
And as a second note, don't let the work break your sleep schedule, it's not a good thing :)

**Comment by biakp** [comment]
Hi @patrickelectric ! I tried to use some 'normal' ways to make a vertical split as you suggested, but I couldn't make it work on the editor :S it looks like windows 98, full of bugs...

**Comment by biakp** [comment]
and well... that is my normal sleeping schedule haha 😞

**Comment by patrickelectric** [comment]
Fixed by #26, thanks!
