### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by filipesaraiva** [patrickelectric/qmlonline#28]
Hey @patrickelectric, congratulations (again) for the project! :)

The project is missing a license and it is recommended to add it before the increase of code from different contributors. You wrote in your [blogpost](https://patrickelectric.work/blog/2020/qmlonline-first-version/) you wold like to submit qmlonline to KDE incubator, so KDE has a [licensing policy](https://community.kde.org/Policies/Licensing_Policy) with some allowed licenses to KDE projects.

If you know which license you would like to apply in the project, I can help you opening a merge request. If you wish discuss about licenses before select some, I can help too. :)

**Comment by patrickelectric** [comment]
Hi Filipe, thank you from bringing this up. 
I have just added a license file based in the kde licensing policy, it's gplv2.
About moving the project, I'm doing some organization in the repository, the gh-pages and master branches are not in sync and I still need to fix the deployment method. 
And about moving to KDE, I'm right now talking with Ben aout CI and the website hosting.

**Comment by filipesaraiva** [comment]
Nice!

**Comment by patrickelectric** [comment]
@filipesaraiva: https://invent.kde.org/webapps/qmlonline

**Comment by patrickelectric** [comment]
@filipesaraiva I kindly update: https://qmlonline.kde.org/
