### ISSUE TITLE
Load a different example each time

### ISSUE THREAD

**Issue by patrickelectric** [patrickelectric/qmlonline#5]

**Comment by peterwx** [comment]
I noticed that there is a similar tool to that of yours that appeared in Qt blog, so in case you want to check it(online, source):
https://qt-webassembly.io/designviewer/
https://git.qt.io/aportale/designviewer

**Comment by patrickelectric** [comment]
Hi @peterwx, thanks for sharing !
But I was unable to load my QML files, it appears that this tool was not made to share and do code prototype in a only environment, so it looks a different thing of what I'm trying to do.

I did try to send some example QML that I have here, but it fail to load since it expects a project. 
![image](https://user-images.githubusercontent.com/1215497/71423461-599ae880-2668-11ea-9a83-22678e6cb983.png)

**Comment by peterwx** [comment]
Yes you are right. The input expected in this other tool are files of a project not source code only - the qml file itself. Nevertheless this other tool may support multiple qml files (not sure).

**Comment by patrickelectric** [comment]
If you want, check [patrickelectric/qhot](https://github.com/patrickelectric/qhot), it does that and with hot reload and multiple QML files plus some options for plugins and translation.

**Comment by peterwx** [comment]
I'll check it later. Thanks for your suggestion.
